Import the numpy module

In [2]:
import numpy as np

Create a 1d numpy array called arr1 that looks like the one below. Display it.

In [3]:
arr1 = np.array([3,  6,  9, 12, 15])
arr1

array([ 3,  6,  9, 12, 15])

Print out the 3rd element of the array.

In [4]:
arr1[2]

9

Create a 2d numpy array called arr2 that looks like the one below. Display it.

In [5]:
arr2 = np.array([[2,  4,  6],[3,  6,  9],[4,  8, 12]])
arr2

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

Print out the element at row index=2, col index=1.

In [6]:
arr2[2,1]

8

Create an array that goes from 0 to 100 with step=3. Display it.

In [7]:
np.arange(0,101,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Create a 10x5 2d array filled with zeroes. Display it.

In [47]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create an array called lin1d, that has 100 data points spaced between 57 and 108. Display it.

In [48]:
lin1d = np.linspace(57,108,100)
lin1d

array([ 57.        ,  57.51515152,  58.03030303,  58.54545455,
        59.06060606,  59.57575758,  60.09090909,  60.60606061,
        61.12121212,  61.63636364,  62.15151515,  62.66666667,
        63.18181818,  63.6969697 ,  64.21212121,  64.72727273,
        65.24242424,  65.75757576,  66.27272727,  66.78787879,
        67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
        69.36363636,  69.87878788,  70.39393939,  70.90909091,
        71.42424242,  71.93939394,  72.45454545,  72.96969697,
        73.48484848,  74.        ,  74.51515152,  75.03030303,
        75.54545455,  76.06060606,  76.57575758,  77.09090909,
        77.60606061,  78.12121212,  78.63636364,  79.15151515,
        79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
        81.72727273,  82.24242424,  82.75757576,  83.27272727,
        83.78787879,  84.3030303 ,  84.81818182,  85.33333333,
        85.84848485,  86.36363636,  86.87878788,  87.39393939,
        87.90909091,  88.42424242,  88.93939394,  89.45

Reshape lin1d to be 10x10 and call it lin2d. Display it.

In [49]:
lin2d = lin1d.reshape(10,10)
lin2d

array([[ 57.        ,  57.51515152,  58.03030303,  58.54545455,
         59.06060606,  59.57575758,  60.09090909,  60.60606061,
         61.12121212,  61.63636364],
       [ 62.15151515,  62.66666667,  63.18181818,  63.6969697 ,
         64.21212121,  64.72727273,  65.24242424,  65.75757576,
         66.27272727,  66.78787879],
       [ 67.3030303 ,  67.81818182,  68.33333333,  68.84848485,
         69.36363636,  69.87878788,  70.39393939,  70.90909091,
         71.42424242,  71.93939394],
       [ 72.45454545,  72.96969697,  73.48484848,  74.        ,
         74.51515152,  75.03030303,  75.54545455,  76.06060606,
         76.57575758,  77.09090909],
       [ 77.60606061,  78.12121212,  78.63636364,  79.15151515,
         79.66666667,  80.18181818,  80.6969697 ,  81.21212121,
         81.72727273,  82.24242424],
       [ 82.75757576,  83.27272727,  83.78787879,  84.3030303 ,
         84.81818182,  85.33333333,  85.84848485,  86.36363636,
         86.87878788,  87.39393939],
       [ 8

Print out the shape of lin1d and lin2d.

In [50]:
print('lin1d:', lin1d.shape)
print('lin2d:', lin2d.shape)

lin1d: (100,)
lin2d: (10, 10)


Generate a 5x5 array of random numbers called nums. Display it.

In [51]:
nums = np.random.rand(5,5)
nums

array([[0.34024107, 0.08313746, 0.33765704, 0.16391986, 0.42325399],
       [0.44562246, 0.3672474 , 0.16962035, 0.2901589 , 0.44155428],
       [0.63563348, 0.44861238, 0.57810209, 0.98144601, 0.05861963],
       [0.12644198, 0.7513453 , 0.82300524, 0.65778031, 0.16417522],
       [0.35588077, 0.65473128, 0.32509694, 0.90585328, 0.46867657]])

Print out the min, max and mean of the nums array.

In [52]:
print('Min:', nums.min())
print('Max:', nums.max())
print('Mean:', nums.mean())

Min: 0.05861962954502642
Max: 0.9814460059513633
Mean: 0.4399125310402283


Multiple the entire array nums x2 and store it back in nums. Display the result.

In [53]:
nums = nums*2
nums

array([[0.68048215, 0.16627492, 0.67531408, 0.32783971, 0.84650797],
       [0.89124492, 0.7344948 , 0.3392407 , 0.58031781, 0.88310856],
       [1.27126696, 0.89722476, 1.15620419, 1.96289201, 0.11723926],
       [0.25288395, 1.50269061, 1.64601049, 1.31556061, 0.32835043],
       [0.71176154, 1.30946256, 0.65019387, 1.81170656, 0.93735315]])

Select row index 1 to 2 and col index 2 to 3 and display the result.

In [54]:
nums[1:3,2:4]

array([[0.3392407 , 0.58031781],
       [1.15620419, 1.96289201]])

Modify that same selection by multiplying it x10, then display the new nums array.

In [55]:
nums[1:3,2:4] = nums[1:3,2:4]*10
nums

array([[ 0.68048215,  0.16627492,  0.67531408,  0.32783971,  0.84650797],
       [ 0.89124492,  0.7344948 ,  3.392407  ,  5.80317809,  0.88310856],
       [ 1.27126696,  0.89722476, 11.56204185, 19.62892012,  0.11723926],
       [ 0.25288395,  1.50269061,  1.64601049,  1.31556061,  0.32835043],
       [ 0.71176154,  1.30946256,  0.65019387,  1.81170656,  0.93735315]])